create HeadingComponent
PfadiMH/puck pull request #11
Opened 2024-12-02 10:40 UTC by 05kl

solves #6

2024-12-09 10:32 UTC, TeamBattino requested changes

2024-12-09 10:32 UTC, TeamBattino commented on puck.config.tsx
> +  HeadingComponent: { text: string, textAlign: string }
Use HeadingComponentProps here

2024-12-09 10:43 UTC, TeamBattino approved these changes
Thanks!

2024-12-16 07:59 UTC, silvio2402 requested changes

2024-12-16 07:59 UTC, silvio2402 commented on components/HeadingComponent.tsx
Please format the file. Tip: turn on format on save

2024-12-16 07:59 UTC, silvio2402 commented on components/HeadingComponent.tsx
> +function HeadingComponent({text, textAlign}: HeadingComponentProps){
Can you rename `HeadingComponent` to just `Heading`?

2024-12-16 07:59 UTC, silvio2402 commented on components/HeadingComponent.tsx
> +    text: "HeadingComponent",
How about `Heading` as a default value?

2024-12-16 07:59 UTC, silvio2402 commented on components/HeadingComponent.tsx
> +    <div style={{padding: 64}}>
Is this padding needed, or is there a way to use the margin and min-height on the h1 tag?

2024-12-16 07:59 UTC, silvio2402 commented on components/HeadingComponent.tsx
> +function HeadingComponent({text, textAlign}: HeadingComponentProps){
Also, make sure the component is export default.

2024-12-16 07:59 UTC, silvio2402 commented on puck.config.tsx
>      },
Since you created the component can you please also remove the HeadingBlock component here. It's no longer needed.

2024-12-16 07:59 UTC, silvio2402 commented on components/HeadingComponent.tsx
Let's also think about what this component does. How can you add different heading levels, like h1, h2 or h3?
I suggest we add a `level` prop to this component and make the user choose it.

2025-02-23 16:28 UTC, merged